apiVersion: v1
kind: ConfigMap
metadata:
  name: repliagent-mongo-config
data:
  mongod.conf: |
    # Injected from Kubernetes Config Map.
    # mongod.conf
    # For documentation of all options, see:
    #   http://docs.mongodb.org/manual/reference/configuration-options/

    # Ensure cloud crap is disabled.
    cloud:
      monitoring:
        free:
          state: 'off'

    # Configure MongoDB Replica Set Node
    net:
      bindIp: '0.0.0.0'
    storage:
      dbPath: /data
      journal:
        enabled: true
      wiredTiger:
        engineConfig:
          # Cap the memory used by mongo data caching.
          cacheSizeGB: 1
    replication:
      oplogSizeMB: 512
      replSetName: lab
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: repliagent-mongo
  name: repliagent-mongo
spec:
  containers:
    - name: mongo
      image: 'docker.io/library/mongo:6'
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 27017
          hostPort: 27017
      command:
        - 'mongod'
        - '--config'
        - '/config/mongod.conf'
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 1000m
          memory: 500Mi
      volumeMounts:
        - name: config
          mountPath: '/config'
          readOnly: true
        - name: tmp
          mountPath: '/tmp'
  volumes:
    - name: config
      configMap:
        name: repliagent-mongo-config
        items:
          - key: 'mongod.conf'
            path: 'mongod.conf'
    - name: tmp
      emptyDir:
        medium: "Memory"
