name: Rust Checks (other versions)

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Prepare for the future!
  check-nightly:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Check Agent
        run: ci/check-workspace.sh Agent Cargo.toml

  # Earliest version of rust supported.
  check-min-rust:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.68.0
          override: true
          components: rustfmt, clippy
      - name: Check Agent
        run: ci/check-workspace.sh Agent Cargo.toml
